swagger: '2.0'
info:
  version: '1.0'
  title: delilahResto
  contact: {}
host: localhost:3000
basePath: /
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    post:
      summary: Crear usuario
      tags:
      - Misc
      operationId: Crearusuario
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CrearusuarioRequest'
      responses:
        200:
          description: ''
          headers: {}
  /login:
    post:
      summary: Login cliente
      tags:
      - Misc
      operationId: Logincliente
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/LoginclienteRequest'
      responses:
        200:
          description: ''
          headers: {}
  /admin/productos:
    post:
      summary: Agregar productos (admin)
      tags:
      - Misc
      operationId: Agregarproductos(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Agregarproductos%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
  /admin/grupoprecio:
    post:
      summary: Agregar grupos(admin)
      tags:
      - Misc
      operationId: Agregargrupos(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Agregargrupos%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: Obetener grupos(admin)
      tags:
      - Misc
      operationId: Obetenergrupos(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /admin/producto_grupo:
    post:
      summary: Agregar producto_grupo(admin)
      tags:
      - Misc
      operationId: Agregarproducto_grupo(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Agregarproducto_grupo%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: Obtener producto_grupo(admin)
      tags:
      - Misc
      operationId: Obtenerproducto_grupo(admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/precio:
    post:
      summary: Agregar precios (admin)
      tags:
      - Misc
      operationId: Agregarprecios(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Agregarprecios%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: Obetener Precios(admin)
      tags:
      - Misc
      operationId: ObetenerPrecios(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /admin/metodopago:
    post:
      summary: Agregar metodo de pago (admin)
      tags:
      - Misc
      operationId: Agregarmetododepago(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Agregarmetododepago%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
  /admin/estadopedido:
    post:
      summary: Agregar estados al pedido
      tags:
      - Misc
      operationId: Agregarestadosalpedido
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AgregarestadosalpedidoRequest'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: Obetener estados de pedidos
      tags:
      - Misc
      operationId: Obetenerestadosdepedidos
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /pedido:
    post:
      summary: Crear pedido
      tags:
      - Misc
      operationId: Crearpedido
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          example:
          - metodo_de_pago: 1
          - producto: 8
            cantidad: 7
          - producto: 6
            cantidad: 3
          - producto: 1
            cantidad: 2
          - producto: 7
            cantidad: 1
          type: array
          items:
            $ref: '#/definitions/CrearpedidoRequest'
      responses:
        200:
          description: ''
          headers: {}
  /infouser:
    post:
      summary: Agregar informacion de perfil
      tags:
      - Misc
      operationId: Agregarinformaciondeperfil
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AgregarinformaciondeperfilRequest'
      responses:
        200:
          description: ''
          headers: {}
    get:
      summary: Obtener informacion perfil
      tags:
      - Misc
      operationId: Obtenerinformacionperfil
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/users:
    get:
      summary: Lista de usuarios (Admin)
      tags:
      - Misc
      operationId: Listadeusuarios(Admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
    put:
      summary: Actualizar datos usuario
      tags:
      - Misc
      operationId: Actualizardatosusuario
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ActualizardatosusuarioRequest'
      responses:
        200:
          description: ''
          headers: {}
  /productos:
    get:
      summary: Obtener productos
      tags:
      - Misc
      operationId: Obtenerproductos
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /pedidos:
    get:
      summary: Obtener precios pedidos
      tags:
      - Misc
      operationId: Obtenerpreciospedidos
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
  /metodopago:
    get:
      summary: Obetener metodos de pago
      tags:
      - Misc
      operationId: Obetenermetodosdepago
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/infousuarios:
    get:
      summary: Obetener infotmacion perfil usuarios (admin)
      tags:
      - Misc
      operationId: Obetenerinfotmacionperfilusuarios(admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/users/1:
    put:
      summary: Actualizar datos usuarios (admin)
      tags:
      - Misc
      operationId: Actualizardatosusuarios(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Actualizardatosusuarios%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
  /admin/5:
    put:
      summary: Actualizar rol a admin (admin)
      tags:
      - Misc
      operationId: Actualizarrolaadmin(admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/productos/2:
    put:
      summary: Actualizar productos (admin)
      tags:
      - Misc
      operationId: Actualizarproductos(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Actualizarproductos%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
  /adm/precio:
    put:
      summary: Actualizar precios (admin)
      tags:
      - Misc
      operationId: Actualizarprecios(admin)
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/Actualizarprecios%28admin%29Request'
      responses:
        200:
          description: ''
          headers: {}
  /adm/estadopedido:
    put:
      summary: Actualizar estado a pedido
      tags:
      - Misc
      operationId: Actualizarestadoapedido
      deprecated: false
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ActualizarestadoapedidoRequest'
      responses:
        200:
          description: ''
          headers: {}
  /admin/productos/4:
    delete:
      summary: Borrar rol de Admin (Admin)
      tags:
      - Misc
      operationId: BorrarroldeAdmin(Admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
  /admin/users/4:
    delete:
      summary: Borrar usuario (Admin)
      tags:
      - Misc
      operationId: Borrarusuario(Admin)
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        required: false
        default: Bearer {token}
        type: string
      responses:
        200:
          description: ''
          headers: {}
definitions:
  CrearusuarioRequest:
    title: CrearusuarioRequest
    example:
      usuario: Uno
      correo: uno@correo.com
      contraseña: Numero
    type: object
    properties:
      usuario:
        type: string
      correo:
        type: string
      contraseña:
        type: string
    required:
    - usuario
    - correo
    - contraseña
  LoginclienteRequest:
    title: LoginclienteRequest
    example:
      usuario: Uno
      contraseña: Numero
    type: object
    properties:
      usuario:
        type: string
      contraseña:
        type: string
    required:
    - usuario
    - contraseña
  LoginadminRequest:
    title: LoginadminRequest
    example:
      usuario: Brayan
      contraseña: 1234
    type: object
    properties:
      usuario:
        type: string
      contraseña:
        type: string
    required:
    - usuario
    - contraseña
  Agregarproductos(admin)Request:
    title: Agregarproductos(admin)Request
    example:
      producto: Camarones
    type: object
    properties:
      producto:
        type: string
    required:
    - producto
  Agregargrupos(admin)Request:
    title: Agregargrupos(admin)Request
    example:
      grupo: Helados
    type: object
    properties:
      grupo:
        type: string
    required:
    - grupo
  Agregarproducto_grupo(admin)Request:
    title: Agregarproducto_grupo(admin)Request
    example:
      id_producto: 8
      id_grupo: 4
    type: object
    properties:
      id_producto:
        type: integer
        format: int32
      id_grupo:
        type: integer
        format: int32
    required:
    - id_producto
    - id_grupo
  Agregarprecios(admin)Request:
    title: Agregarprecios(admin)Request
    example:
      grupo: Hielo extra
      precio: 0
      fecha_ini: 2021-02-24T05:00:00Z
      fecha_fin: 2021-12-31T05:00:00Z
    type: object
    properties:
      grupo:
        type: string
      precio:
        type: integer
        format: int32
      fecha_ini:
        type: string
      fecha_fin:
        type: string
    required:
    - grupo
    - precio
    - fecha_ini
    - fecha_fin
  Agregarmetododepago(admin)Request:
    title: Agregarmetododepago(admin)Request
    example:
      metodo_pago: Tarjeta de credito
    type: object
    properties:
      metodo_pago:
        type: string
    required:
    - metodo_pago
  AgregarestadosalpedidoRequest:
    title: AgregarestadosalpedidoRequest
    example:
      estadoPedido: Cancelado
      esFinal: S
    type: object
    properties:
      estadoPedido:
        type: string
      esFinal:
        type: string
    required:
    - estadoPedido
    - esFinal
  CrearpedidoRequest:
    title: CrearpedidoRequest
    example:
      metodo_de_pago: 1
    type: object
    properties:
      metodo_de_pago:
        type: integer
        format: int32
      producto:
        type: integer
        format: int32
      cantidad:
        type: integer
        format: int32
  AgregarinformaciondeperfilRequest:
    title: AgregarinformaciondeperfilRequest
    example:
      Nombre: Numero Dos
      Celular: 2222222222
      Direccion: Nada ingenioso que agregar
    type: object
    properties:
      Nombre:
        type: string
      Celular:
        type: string
      Direccion:
        type: string
    required:
    - Nombre
    - Celular
    - Direccion
  ActualizardatosusuarioRequest:
    title: ActualizardatosusuarioRequest
    example:
      usuario: Brayan
      contraseña: 1234
    type: object
    properties:
      usuario:
        type: string
      contraseña:
        type: string
    required:
    - usuario
    - contraseña
  Actualizardatosusuarios(admin)Request:
    title: Actualizardatosusuarios(admin)Request
    example:
      usuario: Brayan
      contraseña: 1234
    type: object
    properties:
      usuario:
        type: string
      contraseña:
        type: string
    required:
    - usuario
    - contraseña
  Actualizarproductos(admin)Request:
    title: Actualizarproductos(admin)Request
    example:
      producto: Coca Cola
    type: object
    properties:
      producto:
        type: string
    required:
    - producto
  Actualizarprecios(admin)Request:
    title: Actualizarprecios(admin)Request
    example:
      grupo: Helados
      precio: 5000
      fecha_ini: 2021-02-24T05:00:00Z
      fecha_fin: 2021-12-31T05:00:00Z
    type: object
    properties:
      grupo:
        type: string
      precio:
        type: integer
        format: int32
      fecha_ini:
        type: string
      fecha_fin:
        type: string
    required:
    - grupo
    - precio
    - fecha_ini
    - fecha_fin
  ActualizarestadoapedidoRequest:
    title: ActualizarestadoapedidoRequest
    example:
      id_pedido: 2
      estado_pedido: 3
    type: object
    properties:
      id_pedido:
        type: integer
        format: int32
      estado_pedido:
        type: integer
        format: int32
    required:
    - id_pedido
    - estado_pedido
tags:
- name: Misc
  description: ''
